---
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Differences in Hector outputs

``` {r greeting, echo = FALSE}
cat("Hello, this is `leeyabot`! ")
emo::ji("robot")

```

The current pull request's outputs differ from `master` as follows:


``` {r differences, echo = FALSE, message = FALSE}
# Load packages
library(dplyr)
library(ggplot2)
library(gridExtra)
library(hector)
library(emo)

# Read in v2.5 data
v25 <- read.csv("version25_output.csv")

# Remove first column of numbers (1, 2, 3...)
v25 <- v25 %>% select(scenario, year, variable, value, units)
v25 <- v25 %>% mutate(version = "v2.5.0")

# Read in files for four RCPs - v3
inputdir <- system.file("input", package = "hector")
rcp26 <- file.path(inputdir, "hector_rcp26.ini")
rcp45 <- file.path(inputdir, "hector_rcp45.ini")
rcp60 <- file.path(inputdir, "hector_rcp60.ini")
rcp85 <- file.path(inputdir, "hector_rcp85.ini")

# Variables of interest
vars <- c(ATMOSPHERIC_C(), GLOBAL_TEMP(), RF_TOTAL())
rcps <- c(rcp26, rcp45, rcp60, rcp85)
scenarios <- c("rcp26", "rcp45", "rcp60", "rcp85")

# Function to run core and retrieve variables for each scenario
run_core <- function(scenario, vars) {
    ini <- file.path(inputdir, paste0("hector_", scenario, ".ini"))
    core <- newcore(ini)
    run(core)
    sd <- core$strtdate
    ed <- core$enddate
    fetchvars(core, sd:ed, vars, scenario)
}

# Run function and create v3 data.frame
v3 <- lapply(scenarios, run_core, vars)
v3 <- bind_rows(v3)
v3 <- v3 %>% mutate(version = "v3.0.0")

# Find differences between versions
differences <- v25 %>% mutate(diff = v3$value - v25$value)
differences <- differences %>% select(scenario, year, variable, units, version, diff)
```


```{r summary-table, echo= FALSE}

# Organize data
v3 %>%
    filter(scenario == "rcp45") %>%
    select(value) %>%
    rename(v3 = value) -> new_values

both_versions <- v25 %>%
    filter(scenario == "rcp45") %>%
    select(year, variable, value) %>%
    rename(v25 = value) %>%
    cbind(new_values)

# Define params
years <- both_versions$year

# Compute linear regression
linear <- by(both_versions, both_versions$variable, function(x) lm (both_versions$v3~both_versions$v25))

# Access r squared
squares <- sapply(linear, summary)
squares <- squares %>% 
    as.data.frame() %>%
    slice(8) %>%
    t() -> squares

colnames(squares) <- "R squared"

# Calculate RMSE
# Extract residuals
atmos_res <- linear$atmos_c$residuals
ftot_res <- linear$Ftot$residuals
tgav_res <- linear$Tgav$residuals

table <- cbind(atmos_res, ftot_res, tgav_res)

# Define function
RMSE <- function(res) {
    r <- sqrt(mean(res^2))
}

# Find RMSE
error <- as.data.frame(apply(table, MARGIN = 2, RMSE))
rownames(error) <- c("atmos_c", "Ftot", "Tgav")

# Find mean of data to normalize
mean25 <- by(both_versions$v25, both_versions$variable, mean)
mean25 <- as.data.frame(c(mean25[1], mean25[2], mean25[3]))

# Divide RMSE by means
NRMSE <- as.data.frame(error[,1] / mean25[,1])
rownames(NRMSE) <- c("atmos_c", "Ftot", "Tgav")
colnames(NRMSE) <- "NRMSE"

# Table
summary_table <- cbind(squares, NRMSE)
print(summary_table)

```

``` {r graphs, echo = FALSE, fig.width = 12, fig.height = 9}
# Just the numerical differences
diff_plot <- ggplot(differences, aes(year, diff, color = variable)) +
    geom_line() +
    facet_grid(variable~scenario, scales = "free") +
    scale_color_manual(labels = c("atmos_c (Pg C)", "Ftot (W/m2)", "Tgav (degC)"), values = c("gold", "aquamarine4", "slateblue4")) +
    ggtitle("Differences in Hector outputs in v3.0.0 relative to v2.5.0") +
    labs(x = "Year", y = "Difference in value", col = "Variable") +
    theme_bw()
    
diff_plot

```
