name: test auto comment
on: [push]
jobs:
  test-coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-r@master
        with:
          r-version: 'release'

      - uses: r-lib/actions/setup-pandoc@master

      - name: Install dependencies
        run: |
          install.packages("ggplot2")
        shell: Rscript {0}

      - name: run script 
        run: |
           echo "we are here"
             
      - name: generate comment
        uses: wow-actions/auto-comment@v1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          pullRequestOpened: |
            👋 @{{ author }}
            Thank you for your contribution. Here is how your changes will differ from Hector v2.5.0.
          
          pullRequestEdited: |
            👋 @{{ author }}
            Nice edit. Here is how your updated changes will differ from Hector v2.5.0.
            