name: Modified Auto Comment
on: [push, issues, pull_request]
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: wow-actions/auto-comment@v1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          pullRequestOpened: |
            👋 @{{ author }}
            Thank you for your contribution. Here is how your changes will differ from Hector v2.5.0.
          
          pullRequestEdited: |
            👋 @{{ author }}
            Nice edit. Here is how your updated changes will differ from Hector v2.5.0.
            
          pullRequestClosed: |
            👋 @{{ author }}
            Alright! Here is how this pull request differs from Hector v2.5.0.
            
          issuesOpened: |
            Will this work? 