name: Modified Auto Comment
on: [pull_request]
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: wow-actions/auto-comment@v1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

          pullRequestOpened: |
          Thank you for your contribution. Here is how your changes will differ from Hector v2.5.0.
          script: |
            Rscript "C:\Users\pres520\Documents\comment_test\v3_v25_diff.R"
        
            
