name: report-status
on: [push, pull_request]
jobs:
  run:
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v2
      - uses: iterative/setup-cml@v1
      - uses: r-lib/actions/setup-r@master
        with:
          r-version: 'release'
      - uses: r-lib/actions/setup-pandoc@master

      - name: Install dependencies
        run: |
          install.packages("ggplot2")
          install.packages("dplyr")
          install.packages("curl")
          install.packages("devtools")
          devtools::install_github("jgcri/hector")
          devtools::install_github("hadley/emo")
        shell: Rscript {0}
        
      - name: Generate report
        env:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
        run: |
          rmarkdown::render("OutputDifferences.Rmd", run_pandoc = FALSE)
          cml-send-comment OutputDifferences.md
        shell: Rscript {0}

