name: report-status

on: [push, pull_request]

jobs:
  run:
    runs-on: [ubuntu-latest]
    container: docker://dvcorg/cml-py3:latest
    steps:
      - uses: actions/checkout@v2
      - name: Generate report
        env:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "## Test" > report.md
          file.path("C:\\Users\\pres520\\Documents\\comment_test\\comment")
          cml-publish "Hector output differences by version.jpg" --md >> report.md
          cml-send-comment report.md