name: report-status
on: [push, pull_request]
jobs:
  run:
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v2
      - uses: iterative/setup-cml@v1
      - uses: r-lib/actions/setup-r@master
        with:
          r-version: 'release'
      - uses: r-lib/actions/setup-pandoc@master

      - name: Install dependencies
        run: |
          install.packages("ggplot2")
          install.packages("dplyr")
          install.packages("gridExtra")
          install.packages("remotes")
          remotes::install_github("jgcri/hector")
        shell: Rscript {0}
        
      - name: Generate report
        env:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
        run: |
          Rscript v3_v25_diff.R
          
          echo "## Test" > report.md
          cml-publish "Hector output differences by version.jpg" --md >> report.md
          cml-send-comment report.md
